# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ImagePypelines(object):
    def setupUi(self, ImagePypelines):
        ImagePypelines.setObjectName(_fromUtf8("ImagePypelines"))
        ImagePypelines.resize(1028, 620)
        self.centralwidget = QtGui.QWidget(ImagePypelines)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.graphicswidget = QtGui.QWidget(self.centralwidget)
        self.graphicswidget.setObjectName(_fromUtf8("graphicswidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.graphicswidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.toolBox = QtGui.QToolBox(self.graphicswidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setMinimumSize(QtCore.QSize(200, 0))
        self.toolBox.setObjectName(_fromUtf8("toolBox"))
        self.blockBox = QtGui.QWidget()
        self.blockBox.setGeometry(QtCore.QRect(0, 0, 500, 157))
        self.blockBox.setObjectName(_fromUtf8("blockBox"))
        self.toolBox.addItem(self.blockBox, _fromUtf8(""))
        self.pipelineBox = QtGui.QWidget()
        self.pipelineBox.setObjectName(_fromUtf8("pipelineBox"))
        self.toolBox.addItem(self.pipelineBox, _fromUtf8(""))
        self.backgroundBox = QtGui.QWidget()
        self.backgroundBox.setObjectName(_fromUtf8("backgroundBox"))
        self.toolBox.addItem(self.backgroundBox, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.toolBox)
        self.frame = QtGui.QFrame(self.graphicswidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.pipelineSelector = QtGui.QComboBox(self.frame)
        self.pipelineSelector.setObjectName(_fromUtf8("pipelineSelector"))
        self.verticalLayout_2.addWidget(self.pipelineSelector)
        self.graphicsView = QtGui.QGraphicsView(self.frame)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.verticalLayout_2.addWidget(self.graphicsView)
        self.horizontalLayout.addWidget(self.frame)
        self.verticalLayout.addWidget(self.graphicswidget)
        self.interpwidget = QtInterpreter(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.interpwidget.sizePolicy().hasHeightForWidth())
        self.interpwidget.setSizePolicy(sizePolicy)
        self.interpwidget.setMinimumSize(QtCore.QSize(0, 200))
        self.interpwidget.setObjectName(_fromUtf8("interpwidget"))
        self.verticalLayout.addWidget(self.interpwidget)
        ImagePypelines.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(ImagePypelines)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1028, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuPipeline = QtGui.QMenu(self.menubar)
        self.menuPipeline.setObjectName(_fromUtf8("menuPipeline"))
        self.menuBlock = QtGui.QMenu(self.menubar)
        self.menuBlock.setObjectName(_fromUtf8("menuBlock"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        ImagePypelines.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(ImagePypelines)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        ImagePypelines.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(ImagePypelines)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        ImagePypelines.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionExit = QtGui.QAction(ImagePypelines)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionDelete = QtGui.QAction(ImagePypelines)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDelete.setIcon(icon1)
        self.actionDelete.setObjectName(_fromUtf8("actionDelete"))
        self.actionconnectBlocks = QtGui.QAction(ImagePypelines)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/linepointer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionconnectBlocks.setIcon(icon2)
        self.actionconnectBlocks.setObjectName(_fromUtf8("actionconnectBlocks"))
        self.actionaddItem = QtGui.QAction(ImagePypelines)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/addpipeline.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionaddItem.setIcon(icon3)
        self.actionaddItem.setObjectName(_fromUtf8("actionaddItem"))
        self.actionRun = QtGui.QAction(ImagePypelines)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/run.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRun.setIcon(icon4)
        self.actionRun.setObjectName(_fromUtf8("actionRun"))
        self.actionselect = QtGui.QAction(ImagePypelines)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/select.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionselect.setIcon(icon5)
        self.actionselect.setObjectName(_fromUtf8("actionselect"))
        self.actionNewPipeline = QtGui.QAction(ImagePypelines)
        self.actionNewPipeline.setIcon(icon3)
        self.actionNewPipeline.setObjectName(_fromUtf8("actionNewPipeline"))
        self.actionMove_to_Front = QtGui.QAction(ImagePypelines)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/bringtofront.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMove_to_Front.setIcon(icon6)
        self.actionMove_to_Front.setObjectName(_fromUtf8("actionMove_to_Front"))
        self.actionSend_to_back = QtGui.QAction(ImagePypelines)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/sendtoback.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSend_to_back.setIcon(icon7)
        self.actionSend_to_back.setObjectName(_fromUtf8("actionSend_to_back"))
        self.actionAbout = QtGui.QAction(ImagePypelines)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/about.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon8)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionDelete_Pipeline = QtGui.QAction(ImagePypelines)
        self.actionDelete_Pipeline.setIcon(icon1)
        self.actionDelete_Pipeline.setObjectName(_fromUtf8("actionDelete_Pipeline"))
        self.actionDebug = QtGui.QAction(ImagePypelines)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/bug.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDebug.setIcon(icon9)
        self.actionDebug.setObjectName(_fromUtf8("actionDebug"))
        self.menuFile.addAction(self.actionExit)
        self.menuFile.addSeparator()
        self.menuPipeline.addAction(self.actionNewPipeline)
        self.menuPipeline.addAction(self.actionDelete_Pipeline)
        self.menuPipeline.addSeparator()
        self.menuPipeline.addAction(self.actionRun)
        self.menuBlock.addAction(self.actionMove_to_Front)
        self.menuBlock.addAction(self.actionSend_to_back)
        self.menuBlock.addAction(self.actionconnectBlocks)
        self.menuBlock.addAction(self.actionaddItem)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuPipeline.menuAction())
        self.menubar.addAction(self.menuBlock.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionNewPipeline)
        self.toolBar.addAction(self.actionDelete_Pipeline)
        self.toolBar.addAction(self.actionRun)
        self.toolBar.addAction(self.actionDebug)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionaddItem)
        self.toolBar.addAction(self.actionDelete)
        self.toolBar.addAction(self.actionselect)
        self.toolBar.addAction(self.actionconnectBlocks)
        self.toolBar.addAction(self.actionMove_to_Front)
        self.toolBar.addAction(self.actionSend_to_back)
        self.toolBar.addSeparator()

        self.retranslateUi(ImagePypelines)
        self.toolBox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(ImagePypelines)

    def retranslateUi(self, ImagePypelines):
        ImagePypelines.setWindowTitle(_translate("ImagePypelines", "MainWindow", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.blockBox), _translate("ImagePypelines", "Builtin Blocks", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pipelineBox), _translate("ImagePypelines", "Builtin Pipelines", None))
        self.toolBox.setItemText(self.toolBox.indexOf(self.backgroundBox), _translate("ImagePypelines", "Backgrounds", None))
        self.menuFile.setTitle(_translate("ImagePypelines", "File", None))
        self.menuPipeline.setTitle(_translate("ImagePypelines", "Pipeline", None))
        self.menuBlock.setTitle(_translate("ImagePypelines", "Block", None))
        self.menuHelp.setTitle(_translate("ImagePypelines", "Help", None))
        self.toolBar.setWindowTitle(_translate("ImagePypelines", "toolBar", None))
        self.actionExit.setText(_translate("ImagePypelines", "Exit", None))
        self.actionExit.setToolTip(_translate("ImagePypelines", "Close the application.", None))
        self.actionDelete.setText(_translate("ImagePypelines", "Delete", None))
        self.actionDelete.setToolTip(_translate("ImagePypelines", "Delete the selected item(s)", None))
        self.actionconnectBlocks.setText(_translate("ImagePypelines", "connectBlocks", None))
        self.actionconnectBlocks.setToolTip(_translate("ImagePypelines", "Connect two items", None))
        self.actionaddItem.setText(_translate("ImagePypelines", "addItem", None))
        self.actionaddItem.setToolTip(_translate("ImagePypelines", "Add a blank block", None))
        self.actionRun.setText(_translate("ImagePypelines", "Run", None))
        self.actionRun.setToolTip(_translate("ImagePypelines", "Run the active pipeline", None))
        self.actionRun.setShortcut(_translate("ImagePypelines", "F5", None))
        self.actionselect.setText(_translate("ImagePypelines", "select", None))
        self.actionselect.setToolTip(_translate("ImagePypelines", "Select Mode", None))
        self.actionNewPipeline.setText(_translate("ImagePypelines", "New Pipeline", None))
        self.actionNewPipeline.setShortcut(_translate("ImagePypelines", "Ctrl+N", None))
        self.actionMove_to_Front.setText(_translate("ImagePypelines", "Move to Front", None))
        self.actionMove_to_Front.setToolTip(_translate("ImagePypelines", "Move item to the front", None))
        self.actionSend_to_back.setText(_translate("ImagePypelines", "Send to back", None))
        self.actionSend_to_back.setToolTip(_translate("ImagePypelines", "Send item to the back", None))
        self.actionAbout.setText(_translate("ImagePypelines", "About", None))
        self.actionAbout.setShortcut(_translate("ImagePypelines", "Ctrl+H", None))
        self.actionDelete_Pipeline.setText(_translate("ImagePypelines", "Delete Pipeline", None))
        self.actionDelete_Pipeline.setToolTip(_translate("ImagePypelines", "Delete a Pipeline", None))
        self.actionDebug.setText(_translate("ImagePypelines", "Debug", None))

from QtInterpreter import QtInterpreter
import diagramscene_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    ImagePypelines = QtGui.QMainWindow()
    ui = Ui_ImagePypelines()
    ui.setupUi(ImagePypelines)
    ImagePypelines.show()
    sys.exit(app.exec_())

