rem regenerate the ui and rc files

rem # to regenerate this file run: 
rem # pathToYourPython\Lib\site-packages\PyQt4\pyuic4.bat -x .\main.ui -o mainWindowUI.py
rem # to regenerate this file run: 
rem # pathToYourPython\Lib\site-packages\PyQt4\pyrcc4.exe -py3 .\diagramscene.qrc -o .\diagramscene_rc3.py
rem # pathToYourPython\Lib\site-packages\PyQt4\pyrcc4.exe -py2 .\diagramscene.qrc -o .\diagramscene_rc2.py
rem # NOTE: diagramscene_rc.py is a import alias that will import the correct version,
rem #   which is necesary for the autogenerated ui.py file 


call D:\Python36\Lib\site-packages\PyQt4\pyuic4.bat -x .\main.ui -o mainWindowUI.py
D:\Python36\Lib\site-packages\PyQt4\pyrcc4.exe -py3 .\diagramscene.qrc -o .\diagramscene_rc3.py
D:\Python36\Lib\site-packages\PyQt4\pyrcc4.exe -py2 .\diagramscene.qrc -o .\diagramscene_rc2.py
